// Generates src/data/icons.ts from the installed @dnb/eufemia package.
// For every icon in icons-meta.json we render its React SVG component to static
// markup, normalise the hard-coded #000 to currentColor (so icons follow the
// in-app theme), strip the fixed width/height (sized via CSS), and attach the
// metadata (category, variant, tags). Medium (24px) variants are skipped — the
// gallery shows the default icon.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ICONS_DIR = path.join(__dirname, "../node_modules/@dnb/eufemia/icons");
const META = path.join(ICONS_DIR, "dnb/icons-meta.json");
const OUT = path.join(__dirname, "../src/data/icons.ts");

const CATEGORY_ORDER = ["essentials", "objects", "products", "actions", "navigation"];

const meta = JSON.parse(fs.readFileSync(META, "utf8"));

// Base (16px) icons only — keys not ending in _medium.
const baseNames = Object.keys(meta)
  .filter((k) => !k.endsWith("_medium"))
  .sort();

const clean = (svg) =>
  svg
    // hard-coded black -> theme colour
    .replace(/(stroke|fill)="#000000"/g, '$1="currentColor"')
    .replace(/(stroke|fill)="#000"/g, '$1="currentColor"')
    // drop fixed pixel size; the page sizes via CSS (viewBox is kept)
    .replace(/\s(width|height)="\d+"/g, "")
    // trim the xmlns noise (kept implicit when injected inline)
    .replace(/\sxmlns="http:\/\/www\.w3\.org\/2000\/svg"/g, "");

const icons = [];
for (const name of baseNames) {
  const m = meta[name];
  const mod = await import(`@dnb/eufemia/icons/dnb/${name}.js`);
  const svg = clean(renderToStaticMarkup(React.createElement(mod.default)));
  icons.push({
    name,
    category: m.category || "objects",
    variant: m.variant || "secondary",
    tags: Array.isArray(m.tags) ? m.tags : [],
    svg,
  });
}

// Order by category (per CATEGORY_ORDER) then name.
icons.sort((a, b) => {
  const ci = CATEGORY_ORDER.indexOf(a.category) - CATEGORY_ORDER.indexOf(b.category);
  return ci !== 0 ? ci : a.name.localeCompare(b.name);
});

const header = `// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// Source: @dnb/eufemia icons + dnb/icons-meta.json. Colours normalised to
// currentColor so icons follow the active theme.

export type IconVariant = "primary" | "secondary";

export interface IconEntry {
  name: string;
  category: string;
  variant: IconVariant;
  tags: string[];
  svg: string;
}

export const ICON_CATEGORIES = ${JSON.stringify(CATEGORY_ORDER)} as const;

export const ICONS: IconEntry[] = ${JSON.stringify(icons)};
`;

fs.writeFileSync(OUT, header);

const byCat = {};
for (const i of icons) byCat[i.category] = (byCat[i.category] || 0) + 1;
console.log(`Wrote ${icons.length} icons to ${OUT}`);
console.log("Per category:", byCat);
console.log(`Primary: ${icons.filter((i) => i.variant === "primary").length}, Secondary: ${icons.filter((i) => i.variant === "secondary").length}`);
console.log(`Output size: ${(fs.statSync(OUT).size / 1024).toFixed(0)} KB`);
